### ISSUE TITLE
Make 'chainloop workflow  create --name build --project xy --team abc' idempotent

### ISSUE THREAD

**Issue by habnux** [chainloop-dev/chainloop#1206]
Today, the CLI returns RC=1 if the workflow already exists for the specified name and project. In the interest of automation, it makes sense that this does not fail. However, a warning could still be displayed.

```
chainloop workflow create --name build --project xy --team abc
ERR failed to create workflow: rpc error: code = InvalidArgument desc = validation error: name already taken
echo $?
1
```

**Comment by migmartri** [comment]
This feature will also help here https://github.com/chainloop-dev/chainloop/issues/961

**Comment by jiparis** [comment]
I'm wondering if there are other commands (other "create") commands, where we should also enable such flag. Maybe some generic flag for "recoverable" commands (`--ignore-errors`)

**Comment by habnux** [comment]
> I'm wondering if there are other commands (other "create") commands, where we should also enable such flag. Maybe some generic flag for "recoverable" errors (`--ignore-errors`)

Imo, ignoring errors is never a good choice ... The creation of a clear and comprehensible interface is crucial.

**Comment by migmartri** [comment]
@habnux so would option `b` work for you? https://github.com/chainloop-dev/chainloop/issues/1206#issuecomment-2283973910

offer a specific flag `--skip-if-exists` that will return exit code `0` if the entity already exists?

**Comment by habnux** [comment]
Yes option B is okey. Another idea is to use the `chainloop workflow update ...` with something like `--create` in case a workflow does not already exist, it will be created. But that's probably more a question of taste.

**Comment by migmartri** [comment]
Thanks, @habnux. I think your proposal will require more changes since creation and update might have different numbers of required arguments. i.e we will need to make `project` mandatory on update if we want to make sure we have a valid workflow created after the process. 

In any case, we want to support `chainloop apply` in the future, though, where you provide, for example, a workflow resource that will create or update a workflow similar to kubectl apply in k8s. Would that work for you?
