### ISSUE TITLE
feat: add Helm chart material type

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#684]
This task is about adding support for Helm Chart material types for attestations. 

- It will be a material type that inherits from the `artifact type` (gets uploaded to CAS)
- We should validate that the received artifact is a packaged Helm chart
- We should document its existence as part of our readme and documentation page

You can see an example of how a new type can be added here https://github.com/chainloop-dev/chainloop/pull/356

**Comment by Javirln** [comment]
One of the important topics here is what _validate a Helm chart_ means in this context.

**Comment by migmartri** [comment]
> One of the important topics here is what _validate a Helm chart_ means in this context.

Indeed, that's the tricky part. The purpose of client validations is to add guard-rails to developers, not really security (yet). So from that POV I'd just add whatever is minimum to differentiate any other file vs a Helm Chart.

Thanks for looking into this!

**Comment by Javirln** [comment]
Oki nice, so for the moment, I've added some really basic validations on the client side which is the following:

It inspects the tarball and specifically looks for to files to be present and syntactically valid which are Charts.yaml and values.yaml. Thinking about adding to the list Chart.lock as well since it's pretty straightforward.

How do you folks see it? cc @jiparis @migmartri

**Comment by migmartri** [comment]
See a follow up task https://github.com/chainloop-dev/chainloop/issues/693
