### ISSUE TITLE
Do not auto-create organization by default in the backend

### ISSUE THREAD

**Issue by migmartri** [chainloop-dev/chainloop#831]
Currently, the backend auto-creates and auto-onboards an organization for an-user. We should look into the possibility of removing this flow and if we still want to support it in the CLI, move the logic to the CLI instead. That way other clients have the option to manually handle the use-case 
```[tasklist]
### Tasks
- [x] Do not auto-create the organization
- [x] Handle the fact that the user might not have organization in the CLI
```

**Comment by javirln** [comment]
From a quick overview on the state of things I can relate the following:
- The removal of auto creation of organizations is trivial and does not affect the regular auth workflow
- On the CLI point of view, the orgID a part from the telemetry side, it's used on organization related actions, `set, leave, ls` that, since no organization is attached to the user when calling the endpoints fail with the following error:
```
ERR error setting current org and user: user does not have any organization associated
```

Raised from `WithCurrentUserAndOrgMiddleware` when inspecting memberships.

A new error for those users will be handled on this task: https://github.com/chainloop-dev/chainloop/issues/945 since we want specific error message to be shown to users.

**Comment by migmartri** [comment]
Thanks Javi

Can we raise and handle the new error now and not in the context of the middleware (note that we have some custom handling in root.go or main.go in the cli?

**Comment by javirln** [comment]
> Can we raise and handle the new error now and not in the context of the middleware (note that we have some custom handling in root.go or main.go in the cli?

I can move the extension of the custom error from the other task to this one to handle it here, no problem. My next question is, do we have already the URL that we want to show users to request access so I can send it back on the error?

**Comment by javirln** [comment]
We can have something in the meantime we are adding the new error though, let me have a look at it :)

**Comment by javirln** [comment]
To something like:
```
$ chainloop --insecure  wf update --id 03209e7e-36e9-4cdf-a4ce-4ff9a8543240 --project random
WRN API contacted in insecure mode
ERR You have limited access to the platform, please request access on the following link: https://app.chainloop.dev/request-access
```
